- hosts: all
  become: true
  tasks:

  - name: Update repository index
    ansible.builtin.package:
      update_cache: yes

  - name: Update all packages
    ansible.builtin.package:
      name: "*"
      state: latest